name: Build Release
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: jtdor/build-deb-action@v1
        with:
          buildpackage-opts: --build=binary --no-sign
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: mmdebstrap
          path: 'debian/artifacts/*'
          compression-level: 9
          if-no-files-found: error
